config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  resources :merchant
  resources :item

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/cool' => 'gif#cool'
  get '/sweet' => 'gif#sweet'

  #root to: 'gif#cool'
  root to: 'sessions#new'
  get 'menu/index'

  get 'search/index'
  get 'search/invoice_number'
  get 'search/invoice_date'

  get '/invoice/download', to: 'invoice#download'
  resources :invoice
  get '/invoice/display_pdf/:id', to: 'invoice#display_pdf', as: 'print'
  get '/invoice/display_small_pdf/:id', to: 'invoice#display_small_pdf', as: 'print_small'
  get '/invoice/email_invoice/:id', to: 'invoice#email_invoice', as: 'email'
  delete '/invoice/delete_item/:id', to: 'invoice#delete_item', as: 'delete_item'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :invoice_items
  has_many :invoices, through: :invoice_items
  validates :upc, presence: {message: "Upc required"}
end

app/controllers/item_controller.rb
class ItemController < ApplicationController

  before_action :authorize

  def index
    @item = Item.all

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_index_path
    else
      render 'edit'
    end
  end

  def new
    @item = Item.new

  end



  def create

    @item = Item.new(item_params)

    if @item.save
      flash[:notice] = "Item has been created"
      redirect_to item_index_path
    else
      render 'new'
    end
  end

  private
  def item_params
    params.require(:item).permit(:description,
    :upc,
    :package_counts,
    :unit_cost,
    :case_cost,
    :retail_cost,
    :discount_amount,
    :discount_start_date,
    :mimick_item,
    :mexicana_item,
    :mamas_item,
    :discount_end_date,
    :colby_ridge_item,
    :product_number)

  end
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/item/edit.html.erb
<div class="container">
<h1>Edit Item</h1>
<%= form_for :item, url: item_path, method: :patch do |f| %>


      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@item.errors.count, "error") %> prohibited
            this item from being saved:
          </h2>
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

      <div class="form-group">
        <%= label_tag :description, "Description" %>
        <%= f.text_field :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :upc, "Upc" %>
        <%= f.text_field :upc, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :product_number, "Product #" %>
        <%= f.text_field :product_number, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :package_counts, "Package Counts" %>
        <%= f.text_field :package_counts, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :unit_cost, "Unit Cost" %>
        <%= f.text_field :unit_cost, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :case_cost, "Case Cost" %>
        <%= f.text_field :case_cost, placeholder: "0.00",class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :retail_cost, "Retail Cost" %>
        <%= f.text_field :retail_cost, placeholder: "0.00", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :discount_amount, "Discount Amount" %>
        <%= f.text_field :discount_amount,  placeholder: "0.00", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :discount_start_date, "Discount Start Date" %>
        <% unless :discount_start_date.empty? %>
            <%= f.text_field :discount_start_date, placeholder: "yyyy-mm-dd", class: "form-control" %>
        <% else %>
            <%= f.text_field :discount_start_date.strftime("%Y-%m-%d"), class: "form-control" %>
        <% end %>
      </div>

      <div class="form-group">
        <%= label_tag :discount_end_date, "Discount End Date" %>
        <% unless :discount_end_date.empty? %>
            <%= f.text_field :discount_end_date, placeholder: "yyyy-mm-dd", class: "form-control" %>
        <% else %>
            <%= f.text_field :discount_end_date.strftime("%Y-%m-%d"), class: "form-control" %>
        <% end %>
      </div>

      <div class="form-group">
        <%= label_tag :mimick_item, "Make available for Mimick Distributing" %>
        <%= f.select :mimick_item, options_for_select([['yes', 1], ['no', 0]], @item.mimick_item), class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :mamas_item, "Make available for Mi Mama's" %>
        <%= f.select :mamas_item, options_for_select([['yes', 1], ['no', 0]], @item.mamas_item), class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :mexicana_item, "Make available for La Mexicana" %>
        <%= f.select :mexicana_item, options_for_select([['yes', 1], ['no', 0]], @item.mexicana_item), class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :colby_ridge_item, "Make available for Colby Ridge" %>
        <%= f.select :colby_ridge_item, options_for_select([['yes', 1], ['no', 0]], @item.colby_ridge_item), class: "form-control" %>
      </div>

      <%= submit_tag "Submit", class: "btn btn-primary" %>

<% end %>
<br><br>

</div>

app/views/item/index.html.erb
<div class="container">
  <h1>Products</h1>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Upc</th>
        <th>Product #</th>
        <th>Start</th>
        <th>End</th>
        <th>Amount</th>
      </tr>
      </thead>
      <tbody>
      <% @item.each do |i| %>
          <tr>
            <td><%= i.upc %></td>

            <td><%= i.product_number %></td>

            <% unless i.discount_start_date %>
              <td><%= i.discount_start_date %></td>
            <% else %>
                <td><%= i.discount_start_date.strftime("%Y-%m-%d")  %></td>
            <% end %>

            <% unless i.discount_end_date %>
                <td><%= i.discount_end_date %></td>
            <% else %>
                <td><%= i.discount_end_date.strftime("%Y-%m-%d")  %></td>
            <% end %>

            <td><%= i.discount_amount %></td>
            <td><%= link_to 'Edit', edit_item_path(i), :class => "btn btn-warning"  %></td>
          </tr>




      <% end %>
      </tbody>
    </table>
  </div>

</div>

<br>

app/views/item/new.html.erb
<div class="container">
<h1>Create Product</h1>
<%= form_for :item, url: item_index_path do |f| %>


      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@item.errors.count, "error") %> prohibited
            this item from being saved:
          </h2>
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

      <div class="form-group">
        <%= label_tag :description, "Description" %>
        <%= f.text_field :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :upc, "Upc" %>
        <%= f.text_field :upc, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :product_number, "Product #" %>
        <%= f.text_field :product_number, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :package_counts, "Package Counts" %>
        <%= f.text_field :package_counts, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :unit_cost, "Unit Cost" %>
        <%= f.text_field :unit_cost, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :case_cost, "Case Cost" %>
        <%= f.text_field :case_cost, placeholder: "0.00",class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :retail_cost, "Retail Cost" %>
        <%= f.text_field :retail_cost, placeholder: "0.00", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :discount_amount, "Discount Amount" %>
        <%= f.text_field :discount_amount,  placeholder: "0.00", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :discount_start_date, "Discount Start Date" %>
        <%= f.text_field :discount_start_date, placeholder: "yyyy-mm-dd", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :discount_end_date, "Discount End Date" %>
        <%= f.text_field :discount_end_date, placeholder: "yyyy-mm-dd", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :mimick_item, "Make available for Mimick" %>
        <%= f.select :mimick_item, options_for_select([['yes', 1], ['no', 0]],'no'), class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :mamas_item, "Make available for Mi Mama's" %>
        <%= f.select :mamas_item, options_for_select([['yes', 1], ['no', 0]], 'no'), class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :mexicana_item, "Make available for La Mexicana" %>
        <%= f.select :mexicana_item, options_for_select([['yes', 1], ['no', 0]], 'no'), class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :colby_ridge_item, "Make available for Colby Ridge" %>
        <%= f.select :colby_ridge_item, options_for_select([['yes', 1], ['no', 0]], 'no'), class: "form-control" %>
      </div>

      <%= submit_tag "Submit", class: "btn btn-primary" %>

<% end %>
<br><br>

</div>