config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  resources :merchant
  resources :item

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/cool' => 'gif#cool'
  get '/sweet' => 'gif#sweet'

  #root to: 'gif#cool'
  root to: 'sessions#new'
  get 'menu/index'

  get 'search/index'
  get 'search/invoice_number'
  get 'search/invoice_date'

  get '/invoice/download', to: 'invoice#download'
  resources :invoice
  get '/invoice/display_pdf/:id', to: 'invoice#display_pdf', as: 'print'
  get '/invoice/display_small_pdf/:id', to: 'invoice#display_small_pdf', as: 'print_small'
  get '/invoice/email_invoice/:id', to: 'invoice#email_invoice', as: 'email'
  delete '/invoice/delete_item/:id', to: 'invoice#delete_item', as: 'delete_item'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def invoice_number
    @invoice = Invoice.where('id = ?', params[:invoice_number])
    puts @invoice.inspect
    if @invoice.size == 0
      flash[:error] = "Invoice not found"
      redirect_to search_index_path
    end

  end


  def invoice_date
    start_date = Time.parse(params[:invoice_date])
    end_date = Time.parse(params[:invoice_date]) + 1.day
    @user = User.find(session[:user_id])

    if @user.name == 'cr_admin'
      @invoice = Invoice.where('start_date between ? and ? and account_type = ?', start_date, end_date, 9)
    else
      @invoice = Invoice.where('start_date between ? and ?', start_date, end_date)
    end

    if @invoice.size == 0
      flash[:error] = "No invoices found on #{params[:invoice_date]}"
      redirect_to search_index_path
    end

  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div class="container">
  <h1>Search</h1>

  <%= form_tag(search_invoice_number_path, method: "get") do %>
    <div  class="table-responsive">
      <table class="table">
        <tr>
          <td><%= text_field_tag(:invoice_number, nil, placeholder: 'invoice number') %></td>
          <td><%= submit_tag("Search", class: "btn btn-primary") %></td>
        </tr>
      </table>
    </div>
  <% end %>

  <%= form_tag(search_invoice_date_path, method: "get") do %>
    <div  class="table-responsive">
      <table class="table">
        <tr>
          <td><%= text_field_tag(:invoice_date, nil, placeholder: 'yyyy-mm-dd') %></td>
          <td><%= submit_tag("Search", class: "btn btn-primary") %></td>
        </tr>
      </table>
    </div>
    <% end %>
</div>

app/views/search/invoice_date.html.erb
<div class="container">
  <h1>Invoices</h1>
  <div  class="table-responsive">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Date</th>
        <th>Merchant</th>
      </tr>
      </thead>
      <tbody>
      <% @invoice.each do |i| %>
          <tr>
            <td><%= i.created_at.strftime("%m/%d/%Y" + " %I:%M%p") %></td>
            <td><%= link_to "#{i.merchant.merchant_name+ ' ' + i.merchant.store_number}", invoice_path(i) %></td>

            <!--<td><%= link_to 'Show', invoice_path(i) %></td>-->
            <td><%= link_to 'Edit', edit_invoice_path(i), :class => "btn btn-warning" %></td>
            <!--<td><%= link_to 'Email', email_path(i), :class => "btn btn-warning" %></td>-->

            <td><%= link_to 'Delete', invoice_path(i), :class => "btn btn-warning", method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/search/invoice_number.html.erb
<div class="container">
  <h1>Invoice - <%=@invoice[0].id %></h1>
  <div  class="table-responsive">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Date</th>
        <th>Merchant</th>
      </tr>
      </thead>
      <tbody>
      <% @invoice.each do |i| %>
          <tr>
            <td><%= i.created_at.strftime("%m/%d/%Y" + " %I:%M%p") %></td>
            <td><%= link_to "#{i.merchant.merchant_name+ ' ' + i.merchant.store_number}", invoice_path(i) %></td>

            <!--<td><%= link_to 'Show', invoice_path(i) %></td>-->
            <td><%= link_to 'Edit', edit_invoice_path(i), :class => "btn btn-warning" %></td>
            <!--<td><%= link_to 'Email', email_path(i), :class => "btn btn-warning" %></td>-->

            <td><%= link_to 'Delete', invoice_path(i), :class => "btn btn-warning", method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>