config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  resources :merchant
  resources :item

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/cool' => 'gif#cool'
  get '/sweet' => 'gif#sweet'

  #root to: 'gif#cool'
  root to: 'sessions#new'
  get 'menu/index'

  get 'search/index'
  get 'search/invoice_number'
  get 'search/invoice_date'

  get '/invoice/download', to: 'invoice#download'
  resources :invoice
  get '/invoice/display_pdf/:id', to: 'invoice#display_pdf', as: 'print'
  get '/invoice/display_small_pdf/:id', to: 'invoice#display_small_pdf', as: 'print_small'
  get '/invoice/email_invoice/:id', to: 'invoice#email_invoice', as: 'email'
  delete '/invoice/delete_item/:id', to: 'invoice#delete_item', as: 'delete_item'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :authorize
  def index
    @user = User.find(session[:user_id])

  end
end

app/views/menu/index.html.erb
<div class="container">
  <h1>Main Menu</h1>
  <div  class="table-responsive">
    <table class="table">

        <% if @user.admin? %>
          <!--<ul class="nav nav-pills nav-stacked">-->

            <!--<tr><li><%=	 link_to "Mimick Distributing", new_invoice_path(:account_type =>  1 ) %></li></tr>-->
            <tr><%= link_to 'Mimick Distributing', new_invoice_path(:account_type =>  1 ), :class => "btn btn-primary"  %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "Mi Mama's", new_invoice_path(:account_type =>  0 ) %></li></tr>-->
            <tr><%= link_to "Mi Mama's", new_invoice_path(:account_type =>  0 ), :class => "btn btn-primary"  %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "La Mexicana", new_invoice_path(:account_type =>  7 ) %></li></tr>-->
            <tr><%=	 link_to "La Mexicana", new_invoice_path(:account_type =>  7), :class => "btn btn-primary"  %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "Colby Ridge", new_invoice_path(:account_type =>  9 ) %></li></tr>-->
            <tr><%=	 link_to "Colby Ridge", new_invoice_path(:account_type =>  9), :class => "btn btn-primary"  %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "Download Invoices", invoice_index_path %></li></tr>-->
            <tr><%=	 link_to "Download Invoices", invoice_index_path, :class => "btn btn-warning" %></tr>
            <tr><br><br></tr>
            <tr><%=	 link_to "Search", search_index_path, :class => "btn btn-warning" %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "Add Merchant", new_merchant_path %></li></tr>-->
            <tr><%=	 link_to "Add Merchant", new_merchant_path, :class => "btn btn-warning" %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "Merchants", merchant_index_path %></li></tr>-->
            <tr><%=	 link_to "View Merchants", merchant_index_path, :class => "btn btn-warning" %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "New Product", new_item_path %></li></tr>-->
            <!--<tr>&nbsp</tr>-->

            <!--<tr><li><%=	 link_to "Products", item_index_path %></li></tr>-->
            <tr><%=	 link_to "View Products", item_index_path, :class => "btn btn-warning" %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "Accounts", signup_path %></li></tr>-->
            <tr><%=	 link_to "Admin", signup_path, :class => "btn btn-warning" %></tr>
          <!--</ul>-->
        <% elsif @user.name == 'cr_admin' %>

          <!--<tr><li><%=	 link_to "Colby Ridge", new_invoice_path(:account_type =>  9 ) %></li></tr>-->
          <tr><%=	 link_to "Colby Ridge", new_invoice_path(:account_type =>  9), :class => "btn btn-primary"  %></tr>
          <tr><br><br></tr>

          <!--<tr><li><%=	 link_to "Download Invoices", invoice_index_path %></li></tr>-->
          <tr><%=	 link_to "Download Invoices", invoice_index_path, :class => "btn btn-warning" %></tr>
          <tr><br><br></tr>
          <tr><%=	 link_to "Search", search_index_path, :class => "btn btn-warning" %></tr>
          <tr><br><br></tr>

          <%else%>
          <!--<ul class="nav nav-pills nav-stacked">-->

            <!--<tr><li><%=	 link_to "Mimick Distributing", new_invoice_path(:account_type =>  1 ) %></li></tr>-->
            <tr><%= link_to 'Mimick Distributing', new_invoice_path(:account_type =>  1 ), :class => "btn btn-primary"  %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "Mi Mama's", new_invoice_path(:account_type =>  0 ) %></li></tr>-->
            <tr><%= link_to "Mi Mama's", new_invoice_path(:account_type =>  0 ), :class => "btn btn-primary"  %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "La Mexicana", new_invoice_path(:account_type =>  7 ) %></li></tr>-->
            <tr><%=	 link_to "La Mexicana", new_invoice_path(:account_type =>  7), :class => "btn btn-primary"  %></tr>
            <tr><br><br></tr>

            <!--<tr><li><%=	 link_to "Colby Ridge", new_invoice_path(:account_type =>  9 ) %></li></tr>-->
            <tr><%=	 link_to "Colby Ridge", new_invoice_path(:account_type =>  9), :class => "btn btn-primary"  %></tr>
            <tr><br><br></tr>
          <!--</ul>-->
        <% end %>

    </table>
  </div>
</div>