config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  resources :merchant
  resources :item

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/cool' => 'gif#cool'
  get '/sweet' => 'gif#sweet'

  #root to: 'gif#cool'
  root to: 'sessions#new'
  get 'menu/index'

  get 'search/index'
  get 'search/invoice_number'
  get 'search/invoice_date'

  get '/invoice/download', to: 'invoice#download'
  resources :invoice
  get '/invoice/display_pdf/:id', to: 'invoice#display_pdf', as: 'print'
  get '/invoice/display_small_pdf/:id', to: 'invoice#display_small_pdf', as: 'print_small'
  get '/invoice/email_invoice/:id', to: 'invoice#email_invoice', as: 'email'
  delete '/invoice/delete_item/:id', to: 'invoice#delete_item', as: 'delete_item'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :merchant
  belongs_to :user
  has_many :invoice_items
  has_many :items, through: :invoice_items
  validates :merchant_id, presence: {message: "Must select merchant"}



  def self.to_csv
    attributes = %w{id start_date merchant_name cost}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |invoice|
        csv << attributes.map{ |attr| invoice.send(attr) }
      end
    end
  end
  def cost
    "#{invoice_items.cost}"
  end

  def merchant_name

      "#{merchant.merchant_name}"

  end

  def user_name
    "#{user.name}"
  end
end

app/controllers/invoice_controller.rb
class InvoiceController < ApplicationController

  before_action :authorize

  def index

  end

  def new
#using heroku stack 22
    @account_type =  params[:account_type]
    @invoice = Invoice.new

    case @account_type
      when "0"
        @item = Item.where(mamas_item: true)
      when "1"
        @item = Item.where(mimick_item: true)
      when "7"
        @item = Item.where(mexicana_item: true)
      when "9"
        @item = Item.where(colby_ridge_item: true)
    end


  end

  def show
    @invoice = Invoice.find(params[:id])


  end

  def create
    @invoice = Invoice.new(invoice_params)
    account_type = @invoice.merchant.account_type


    if params[:selections].blank?
      flash[:danger] = 'Must select at least one item'
      redirect_to :controller => 'invoice', :action => 'new' and return
    end

    @items = Item.find(params[:selections])
    @invoice.user_id = session[:user_id]
    puts 'mmmmmmmm'
    puts params[:invoice].fetch(:merchant_id)
    merchant = Merchant.find(params[:invoice].fetch(:merchant_id))
    puts 'zzz-1111'
    puts merchant.inspect
    @invoice.account_type = merchant.account_type

    #@invoice.start_date = Time.new-21600
    @invoice.start_date = Time.new
    puts @invoice.start_date


    if @invoice.save
      flash[:notice] = "Invoice has been created"
      puts 'zzz-invoice_controller.create'
      puts params.inspect
      #use text input instead of checkboxes
      case account_type
        when 0
          item_list = Item.where(mamas_item: true)
        when 1
          item_list = Item.where(mimick_item: true)
        when 7
          item_list = Item.where(mexicana_item: true)
        when 9
          item_list = Item.where(mexicana_item: true)
      end
      item_list.each do |i|
        if params['quantity' + i.id.to_s] == ""
          puts 'no quantity'
          puts 'quantity'+ i.id.to_s
        else
          puts 'yes quantity'
          puts 'quantity'+ i.id.to_s
        end
      end

      params[:selections].each do |i|
        item = Item.find(i)
        cart = InvoiceItem.new
        cart.invoice = @invoice
        cart.item = item
        cart.quantity = params['quantity' + i.to_s]

        if @invoice.merchant.discount == 'yes' and !item.discount_start_date.nil? and !item.discount_end_date.nil?
          range = item.discount_start_date.strftime("%Y-%m-%d")..item.discount_end_date.strftime("%Y-%m-%d")
          if range.include?(Time.now.strftime("%Y-%m-%d"))
            puts item.discount_amount
            discounted_item_cost =  item.unit_cost - item.discount_amount
            cart.cost = discounted_item_cost * cart.quantity
            cart.discounted_item = "*"
            cart
          else
            cart.cost = item.unit_cost * cart.quantity
          end
        else
          cart.cost = item.unit_cost * cart.quantity
        end
        @invoice.invoice_items << cart
      end

      if @invoice.save
        redirect_to @invoice
      else
        render 'new'
      end
    else
       render 'new'
    end
  end

  def update
    @invoice = Invoice.find(params[:id])
    @invoiceItems = Hash.new

    @invoice.invoice_items.each do |ii|
      @invoiceItems[ii.item_id] = ii.id
    end

    @invoice.user_id = session[:user_id]
    flash[:notice] = "Invoice has been updated"
    params[:selections].each do |i|
      item = Item.find(i)
      if @invoiceItems.member?(item.id)
        unless params['quantity' + i.to_s].blank?
          cart = InvoiceItem.find (@invoiceItems[item.id])
          cart.quantity = params['quantity' + i.to_s]
          if @invoice.merchant.discount == 'yes' and !item.discount_start_date.nil? and !item.discount_end_date.nil?
            range = item.discount_start_date.strftime("%Y-%m-%d")..item.discount_end_date.strftime("%Y-%m-%d")
            if range.include?(Time.now.strftime("%Y-%m-%d"))
              discounted_item_cost =  item.unit_cost - item.discount_amount
              cart.cost = discounted_item_cost * cart.quantity
            else
              cart.cost = item.unit_cost * cart.quantity
            end
          else
            cart.cost = item.unit_cost * cart.quantity
          end
          @invoice.invoice_items << cart
        end
      else
        cart = InvoiceItem.new
        cart.invoice = @invoice
        cart.item = item
        cart.quantity = params['quantity' + i.to_s]
        if @invoice.merchant.discount == 'yes' and !item.discount_start_date.nil? and !item.discount_end_date.nil?
          range = item.discount_start_date.strftime("%Y-%m-%d")..item.discount_end_date.strftime("%Y-%m-%d")
          if range.include?(Time.now.strftime("%Y-%m-%d"))
            discounted_item_cost =  item.unit_cost - item.discount_amount
            cart.cost = discounted_item_cost * cart.quantity
          else
            cart.cost = item.unit_cost * x.quantity
          end
        else
          cart.cost = item.unit_cost * cart.quantity
        end
        @invoice.invoice_items << cart
      end
    end

    if @invoice.update(invoice_params)
      redirect_to @invoice
    else
      render 'edit'
    end
  end

  def edit
    inv = Invoice.find(params[:id])
    m = Merchant.find(inv.merchant_id)

    case m.account_type
      when 0
        @items = Item.where("mamas_item = 1")
      when 1
        @items = Item.where("mimick_item = 1 or mexicana_item = 1")
      when 9
        @items = Item.where("colby_ridge_item = 1")
      when 7
        @items = Item.where("mexicana_item = 1")
    end

    #@items = Item.all
    @invoiceItems = Hash.new
    @quantities = Hash.new
    @invoice = Invoice.find(params[:id])

    @invoice.invoice_items.each do |ii|
      @invoiceItems[ii.item_id] = ii.id
      @quantities[ii.item_id] = ii.quantity
    end
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    redirect_to invoice_index_path
  end

  def delete_item
    @item = InvoiceItem.find(params[:id])
    @item.destroy
    redirect_to action: "edit", id: params[:invoice]
  end

  def display_pdf
    #<%= link_to 'Print', print_path(:invoice => @invoice, format: "pdf"),  :class => "btn btn-primary"  %>
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        #pdf = InvoicePdf.new(@invoice)
        pdf = InvoicePdf.new(@invoice)
        send_data pdf.render,
        filename: "#{@invoice.id}-#{@invoice.merchant.merchant_name}-#{@invoice.merchant.store_number}-invoice.pdf",
        type: 'application/pdf',
        disposition: 'inline'
      end
    end
  end

  def display_small_pdf
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = SmallInvoicePdf.new(@invoice)
        send_data pdf.render,
                  filename: "#{@invoice.id}-#{@invoice.merchant.merchant_name}-#{@invoice.merchant.store_number}-invoice.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end


  def download2
    invoices = Invoice.where("start_date between ? and ? and account_type = ?", params[:start_date], params[:end_date], params[:account_type]).order({ start_date: :asc })
    puts invoices
    invoice_ids = Array.new
    invoices.each do |i|
      invoice_ids << i.id
    end
    if invoice_ids.empty?
      flash[:danger] = "No invoices found dates #{ params[:start_date]} and #{ params[:end_date]}"
      redirect_to invoice_index_path
    else
      #@invoice_items = InvoiceItems.joins(:invoice_items, :merchant)#.where(:id => invoice_ids).group(:id).order("sum(invoice_items.cost) DESC")
      #@invoice_items = Invoice.joins(:invoice_items).where(:id => invoice_ids)
      #@invoice_items = Invoice.includes(:invoice_items, :merchants).where(:id => invoice_ids)#.group(:id, :start_date, 'merchants.merchant_name').order("sum(invoice_items.cost)")
      #@invoice_items = InvoiceItem.where(:invoice_id => invoice_ids).group(:Invoice_id)#.order("sum(invoice_items.cost) DESC")
      @invoice_items = InvoiceDownload.where(:invoice_id => invoice_ids)

      puts 'ddddddddd'
      puts @invoice_items.inspect
      #puts @invoice_summary.inspect
      respond_to do |format|
        format.html
        format.csv {send_data @invoice_items.to_csv, filename: "invoice-#{Date.today}.csv"}
      end
    end
  end


  def download
    credit_total = 0.0
    debit_total = 0.0
    end_date = Time.parse(params[:end_date]) + 1.day
    invoices = Invoice
                    .joins(:invoice_items, :merchant)
                    .group(:invoice_id)
                    .where("invoices.created_at between ? and ? and invoices.account_type = ?", params[:start_date], end_date.strftime('%Y/%m/%d'), params[:account_type])
                    .order('invoices.created_at', 'merchant_id', 'merchants.store_number')
                    .select('invoices.created_at, merchant_id, merchants.store_number, sum(invoice_items.cost) as total, invoices.id')


    if invoices.empty?
      flash[:danger] = "No invoices found dates #{ params[:start_date]} and #{ params[:end_date]}"
      redirect_to invoice_index_path
    else
      invoices.each do |i|
        if i.total > 0
          credit_total += i.total
        else
          debit_total += i.total
        end
    end

      export_dd = []
      first_line = true

      CSV.open("invoice_download_#{Date.today}.csv", "wb") do |csv|
        invoices.each do |invoice|
          if first_line
            export_dd = %w(Invoice_Date Merchant Store_Number Cost Credit Invoice_Number)
            csv << export_dd
            export_dd = []
            first_line = false
          end
          export_dd << invoice.created_at.strftime('%m/%d/%Y')
          export_dd << invoice.merchant.merchant_name
          export_dd << invoice.merchant.store_number
          export_dd << (invoice.total > 0.0 ? invoice.total : nil)
          export_dd << (invoice.total < 0.0 ? invoice.total : nil)

app/views/invoice/create.html.erb
<h1>Invoice#create</h1>
<p>Find me in app/views/invoice/create.html.erb</p>

app/views/invoice/edit.html.erb
<div class="container">
  <h1>Edit Invoice</h1>
  <%= form_for :invoice,  html: {id: 'invoice_new'}, url: invoice_path, method: :patch do |f| %>

      <% if @invoice.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@invoice.errors.count, "error") %> prohibited
              this invoice from being saved:
            </h2>
            <ul>
              <% @invoice.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= label_tag :merchant, "Merchant" %>
        <%= f.select :merchant_id, Merchant.all.collect {|m| [m.merchant_name, m.id]}, include_blank: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :start_date, "Date" %>
        <%= f.text_field :start_date, value: @invoice.start_date.strftime("%Y-%m-%d"), readonly: "readonly", class: "form-control" %>
      </div>


      <div class="form-group">
        <%= label_tag :description, "Product Description" %>
        <%= f.text_field :description, class: "form-control" %>
      </div>

      <div class="table-responsive", class="table table-striped">
        <table class="table">
          <tr>
            <td><h4>Quantity</h4></td>
            <td><h4>Item</h4></td>
            <td></td>
          </tr>
          <br><br>

      <% @items.each do |i|%>
              <% if @invoiceItems.member?(i.id)%>
                 <tr>
                   <td><%= number_field_tag "quantity" + i.id.to_s,  @quantities[i.id], placeholder: "0",  class: "box_text", size: "3" %></td>
                   <td><%= label_tag :item, i.upc %></td>
                   <td><%= check_box_tag 'selections[]', i.id, true, class: "quantity" + i.id.to_s %></td>
                   <td><%= link_to 'Delete', delete_item_path(:id => @invoiceItems[i.id], :invoice => @invoice), method: :delete, data: {confirm: 'Are you sure?'} %></td>
                 </tr>
              <% else %>
                 <tr>
                   <td><%= number_field_tag "quantity" + i.id.to_s,  nil, placeholder: "0",  class: "box_text", size: "3" %></td>
                   <td><%= label_tag :item, i.upc %></td>
                   <td><%= check_box_tag 'selections[]', i.id, false, class: "quantity" + i.id.to_s %></td>
                 </tr>
              <% end %>
          <% end %>
        </table>
      </div>

      <%= submit_tag "Update", class: "btn btn-primary" %>
      <%= link_to 'Back', invoice_path, :class => "btn btn-warning" %>

  <% end %>
  <br><br>


</div>

app/views/invoice/index.html.erb
<div class="container">
  <h1>Download Invoices</h1>
  <%= form_tag invoice_download_path(format: "csv"), method: 'get' do %>
      <div  class="table-responsive">
        <table class="table">
          <tr>
            <%if @current_user.name == 'cr_admin'%>
              <td><b>Account Type:</b>  &ensp;<%= select_tag "account_type", options_for_select([["Colby Ridge",9]],'Colby Ridge') %></td>
            <%else%>
              <td><b>Account Type:</b>  &ensp;<%= select_tag "account_type", options_for_select([["Mi Mama's",0], ['La Mexicana', 7], ['Mimick Distributing', 1], ["Colby Ridge",9]],'Mammas') %></td>
            <%end%>
          </tr>
          <tr>
            <td><b>Start Date:</b><%= text_field_tag :start_date, nil,  class: "form-control", size: "1", value: "#{Time.now.strftime("%Y-%m-%d")}" %></td>
          </tr>
          <tr>
            <td><b>End Date:</b>  &ensp;<%= text_field_tag :end_date, nil,  class: "form-control", size: "1", value: "#{Time.now.strftime("%Y-%m-%d")}" %></td>
          </tr>
          <tr>
            <td><%= submit_tag "Download", class: "btn btn-primary", id: "sub" %></td></td>
            <td></td>
          </tr>
        </table>
      </div>
  <% end %>
</div>

app/views/invoice/new.html.erb
<div class="container">
<h1>Create Invoice</h1>
<%= form_for :invoice,  html: {id: 'invoice_new'}, url: invoice_index_path do |f| %>

    <% if @invoice.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@invoice.errors.count, "error") %> prohibited
            this invoice from being saved:
          </h2>
          <ul>
            <% @invoice.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

      <div class="form-group">
        <%= label_tag :merchant, "Merchant" %>
        <% if @account_type == '0' %>
          <%= f.select :merchant_id, Merchant.where('account_type = 0').order(merchant_name: :asc, store_number: :asc).collect {|m| [m.merchant_name + '-' + m.store_number, m.id]}, include_blank: true, class: "form-control" %>
        <% end %>
        <% if @account_type == '1' %>
          <%= f.select :merchant_id, Merchant.where('account_type = 1').order(merchant_name: :asc, store_number: :asc).collect {|m| [m.merchant_name + '-' + m.store_number, m.id]}, include_blank: true, class: "form-control" %>
        <% end %>
        <% if @account_type == '7' %>
            <%= f.select :merchant_id, Merchant.where('account_type = 0').order(merchant_name: :asc, store_number: :asc).collect {|m| [m.merchant_name + '-' + m.store_number, m.id]}, include_blank: true, class: "form-control" %>
        <% end %>
        <% if @account_type == '9' %>
            <%= f.select :merchant_id, Merchant.where('account_type = 9').order(merchant_name: :asc, store_number: :asc).collect {|m| [m.merchant_name + '-' + m.store_number, m.id]}, include_blank: true, class: "form-control" %>
        <% end %>
      </div>

      <div class="form-group">
        <%= label_tag :start_date, "Date" %>
        <%= f.text_field :start_date, class: "form-control", value: "#{Time.now.strftime("%Y-%m-%d")}", readonly: "readonly" %>
      </div>




      <div class="form-group">
        <%= label_tag :description, "Description" %>
        <%= f.text_field :description, class: "form-control" %>
      </div>

      <div class="table-responsive">
        <table class="table table-condensed">
          <tr>
            <td><h4>Quantity</h4></td>
            <td><h4>Item</h4></td>
            <td><h4>Product #</h4></td>
            <td></td>
          </tr>
          <br><br>
          <% @item.each do |i| %>
              <tr>
                <td><%= number_field_tag "quantity" + i.id.to_s,  nil, placeholder: "0",  class: "box_text", size: "3" %></td>
                <td><%= label_tag :item, i.upc %></td>
                <% v = i.product_number == nil ? '' : i.product_number %>
                <td><%= label_tag :product_number, v %></td>
                <td><%= check_box_tag 'selections[]', i.id,  false, class: "quantity" + i.id.to_s %></td>
              </tr>
          <% end %>
        </table>

      </div>
      <%= submit_tag "Submit", class: "btn btn-primary" %>
<br><br>
<% end %>

</div>

app/views/invoice/show.html.erb
<div class="container">
  <h4><%= @invoice.merchant.merchant_name %></h4>
  <h4>Store #: <%= @invoice.merchant.store_number%></h4>
  <h4>Invoice #: <%= @invoice.id%> </h4>
  <h4><%= @invoice.merchant.address1 %></h4>
  <h7><%= @invoice.created_at.strftime("%m/%d/%Y" + " %I:%M%p") %></h7>




  <div class="table-responsive", class="table table-striped">
    <table class="table">
      <thead>
      <tr>
        <th>Upc</th>
        <th>Quantity</th>
        <th>Cost</th>
      </tr>
      </thead>

      <tbody>
    <% total = 0.0%>
    <% quantity_total = 0.0%>
      <% @invoice.invoice_items.each do |ii|%>
        <tr>
          <td><%= ii.item.upc %></td>
          <td><%= ii.quantity %></td>
          <% quantity_total += ii.quantity %>
          <td>
            <% if ii.discounted_item == "*"%>
              *
              <%= ii.cost %></td>
            <% else %>
                <%= ii.cost %></td>
            <% end %>
          <td><% total += ii.cost %></td>
        </tr>
      <% end %>
      <tr>
        <td>Grand Total</td>
        <td><%= quantity_total %></td>
        <td><%= total %></td>
      </tr>

      </tbody>


    </table>
    <!--<td><%= link_to 'Show', invoice_path %></td>-->
    <td><%= link_to 'Edit', edit_invoice_path(@invoice), :class => "btn btn-warning" %></td>
    <!-- <td><%= link_to 'Delete', invoice_path, method: :delete, data: {confirm: 'Are you sure?'} %></td> -->



    <%= link_to 'Print', print_small_path(:invoice => @invoice, format: "pdf"),  :class => "btn btn-primary"  %>
  </div>
</div>